# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  kvserver:
    image: bazel/production/packaging/aws/data_server:server_docker_image
    entrypoint:
    - /init_server_basic
    - --
    - --port=2000
    - --delta_directory=/srvdata/deltas
    - --realtime_directory=/srvdata/realtime_data
    hostname: kv-server
    networks:
    - kvserver-net
    volumes:
    - type: bind
      read_only: true
      source: ${SUT_DATA_DIR}/kvserver/data
      target: /srvdata/deltas
    - type: tmpfs
      target: /srvdata/realtime_data
      tmpfs:
        size: 1MB
    security_opt:
      - seccomp:unconfined

networks:
  kvserver-net:
    name: no-udf-kvserver
    driver: bridge
