# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# REGION will be replaced with the region set in terraform
# WORKSPACE_ID will be replaced with the region set in terraform
extensions:
  health_check:
  sigv4auth:
    service: "aps"
    region: $REGION

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
      http:
        endpoint: 127.0.0.1:4318
  awsxray:
    endpoint: 127.0.0.1:2000
    transport: udp

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s
  batch/logs:
    timeout: 60s

exporters:
  awscloudwatchlogs:
    log_group_name: "kv-server-log-group"
    log_stream_name: "kv-server-log-stream"
  awsxray:
    index_all_attributes: true
  awsemf:
    namespace: 'KV-Server'
    resource_to_telemetry_conversion:
        enabled: true
    retain_initial_value_of_delta_metric: true
  prometheusremotewrite:
    endpoint: "https://aps-workspaces.$REGION.amazonaws.com/workspaces/$WORKSPACE_ID/api/v1/remote_write"
    auth:
      authenticator: sigv4auth

service:
  pipelines:
    traces:
      receivers: [otlp,awsxray]
      processors: [batch/traces]
      exporters: [awsxray]
    # Metrics are exported to both Cloudwatch and Amazon Managed Prometheus.
    metrics/1:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [awsemf]
    metrics/2:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch/logs]
      exporters: [awscloudwatchlogs]
  extensions: [health_check,sigv4auth]
